---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server-5.6
#   - libselinux-python
#   - libsemanage-python

- name: Install mysql-python via pip
  pip: name=mysql-python state=present

#- name: Configure SELinux to start mysql on any port
#  seboolean: name=mysql_connect_any state=true persistent=yes
#  when: sestatus.rc != 0

- name: Create Mysql configuration file
  template: src=/vagrant/site_config/mysql/my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
  - restart mysql

- name: Restart Mysql Service
  command: /etc/init.d/mysql restart


#- name: insert iptables rule
#  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
#              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
#  notify: restart iptables

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
